### ISSUE TITLE
[BOT] Support server link on top.gg

### ISSUE THREAD

**Issue by fabianneufang** [countr/countr#25] opened 2020-05-02 09:05 UTC
# Bug

The invite link to the support server on top.gg and/or other platforms is/are invalid.

## Reproducing

1. Go to https://top.gg/bot/countr
2. Click "Join Support Server"

## Expected behavior

You should be able to join the server.

## Screenshots

https://cursed-images.xyz/i/5h01qcfb.png

**Comment by promise** [comment] 2020-05-02 09:12
This is not a bug with the source code of Countr. Closing.

**Closed as completed by promise** 2020-05-02 09:12 UTC
